### ISSUE TITLE
⬆ Upgrade EKS Cluster

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops-monitor#119]
The EKS cluster is currently on version 1.23 and should be upgraded to 1.24 or 1.25 if possible in one jump.

Work should be done to establish what pre-requisite activity need to be undertaken and tickets should be created for these pre-requisites.

**Comment by tomwells98** [comment]
Needs to be done by October

**Comment by Gary-H9** [comment]
Upgraded to v1.24. 
Manually upgraded compute resources. 

Upgraded to v1.25. 
Manually upgraded compute resources.
