### ISSUE TITLE
SPIKE - Grafana metrics 

### ISSUE THREAD

**Issue by juddin927** [ministryofjustice/nvvs-devops-monitor#166]
### User Story

 The metrics of this application are exposed to the public. This publicly available page may allow an attacker to retrieve internal information about the application and potentially use it for a more sophisticated attack. The metrics can be viewed here: https://monitoring-alerting.staff.service.justice.gov.uk/metrics
Some Grafana documentation about the metrics pages can be found here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#metrics
And here: https://grafana.com/docs/grafana/latest/setup-grafana/set-up-grafana-monitoring/
If you find that there is no issue in the exposure, please let me know - I hope this helps!

### Value / Purpose

ensure we are not exposing any information that could pivot being a target by the attacker.

### Useful Contacts

Jacob Burton - TVM Analyst

### Definition of Done

- [ ] remove displaying default metrics 
- [ ] README/documentation has been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by tomwells98** [comment]
Need to speak to old team (Mitch etc)

**Comment by tomwells98** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/NVVS-DevOps-622a0b371800e400133bb924/issues/ministryofjustice/nvvs-devops-monitor/166?planning-poker) with Zenhub @juddin927 @smjmoj @darey-io @satishgummadellimoj

**Comment by jennycasanova** [comment]
Emailed Jacob Burton to confirm that we would attempt to pull this ticket into sprint commencing 2nd August 2023.

**Comment by darey-io** [comment]
The Prometheus metrics and grafana dashboard are indeed exposed to the internet, even without the VPN. Therefore this must be addressed as there is indeed security concerns.

Here are some suggested actions we can take:

1. Replace the Ingress controller Loadbalancer to use a private NLB
2. Reuse the same public facing NLB, but restrict access to the subnet through NACL by white listing specific address range (If known)
3. Configure the white listing directly through the ingress controller using an annotation
4. Introduce Network policy within the cluster (Will need to check that the networking plugin in the cluster already supports this)
5. Configure the endpoint to be routed only through the VPN (Will probably require a different team's involvement here)

**Comment by darey-io** [comment]
Option number 3 was considered and tested. After implementing this option, it was observed that the client IP was not preserved and the proxy was only seeing the IP from within the network. For this reason, it is not possible to whitelist required IPs

**Comment by darey-io** [comment]
An authentication strategy was discussed and implemented. Now the endpoint is protected behind a basic auth. as you can see in the screenshot [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGNDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--98b5575e0464aaeaf53c2988ecb9d10046ffd517/image.png)

**Comment by darey-io** [comment]
The concern here is we don't know if this will break anything in the system that relies on /metrics endpoint.. Hence, in Dev environment I have started keeping an eye in the logs, or if there will be any kind of notification complaining about being unable to access the endpoint.
