### ISSUE TITLE
(On Jira) NACs Failed to start ECS task alert config review

### ISSUE THREAD

**Issue by juddin927** [ministryofjustice/nvvs-devops-monitor#225]
### User Story

This critical alert generated where there were no real events registered within the ECS cluster. Also the Alert description need updating as it has reference to pre-production where as the alert being generated by the production environment.

Definition of done 

- [ ] Verify Alerting is fit for purpose
- [ ] "Failed to start task" metric configuration is valid i.e sum,maximum,minimum
- [ ] Fix the typo

### Value / Purpose

it is crucial that we get the effective alerting in place to ensure we are not spending time and effort in investigating a false positive alert. also it is a reputation issue for the team 

### Additional Information

 alert: Failed to start task Production
      expr: aws_mojo_nac_requests_failed_to_start_task_sum{account_id="{{ .Values.production_account_id }}" } > 0
      for: 1m
      labels:
        severity: critical
        service: Network Access Control
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: Failed to start task
        description: An unhealthy container has been released, failed to start task count is {{ "{{ $value }}" }}
        grafana_dashboard_url: https://monitoring-alerting.staff.service.justice.gov.uk/d/sx5ovCb7z/pre-production-network-access-control

### Definition of Done

- [ ] Configuration updated 
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by darey-io** [comment]
Started investigating this. I couldn't access both pre-preprod and prod cluster in other to evaluate further from prometheus. 

Will continue working on this today
