### ISSUE TITLE
Proper environment separation of the monitoring stack

### ISSUE THREAD

**Issue by darey-io** [ministryofjustice/nvvs-devops-monitor#227]
The current deployment of the monitoring stack combines dev, preprod and production in the same configuration. This causes issues especially during development in dev.

This ticket is to properly separate concerns and only have configurations relevant to each environment deployed as required.

For example, during a development work, a slack conversation was flagged based on a production related alert here https://mojdt.slack.com/archives/C04MN9N2ZKN/p1701078906199779

The configuration that caused this is found below:

https://github.com/ministryofjustice/nvvs-devops-monitor/blob/main/k8s-helm-charts/cns-team-monitoring/templates/dns-dhcp-alert-rules.yaml#L164

With Production grafana URL configured regardless of the environment as seen here https://github.com/ministryofjustice/nvvs-devops-monitor/blob/main/k8s-helm-charts/cns-team-monitoring/templates/dns-dhcp-alert-rules.yaml#L166

Another example is where all environments are being monitored:
https://github.com/ministryofjustice/nvvs-devops-monitor/blob/main/k8s-values/values.kube-prometheus-stack.yaml#L36

Hence, we need to properly configure the code base for adequate environment separation

**Comment by smjmoj** [comment]
This ticket will be covered by this SPIKE
https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/nvvs-devops/542
