### ISSUE TITLE
Monitoring tools deployed are not versioned

### ISSUE THREAD

**Issue by darey-io** [ministryofjustice/nvvs-devops-monitor#228]
Prometheus stack, Grafana, Thanos and all the monitoring tools deployed with helm are not versioned.

This can lead to a serious issue where;

1. It becomes hard to roll back to a known good version
2. It can lead to a breaking un-intended release as the pipeline will always seek to upgrade to the latest version

**Comment by tomwells98** [comment]
think this is a duplicate but need Dare to confirm
