### ISSUE TITLE
🤼 Manage GitHub collaborators via Code

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops-monitor#38]
We need to manage github collaborators via the method outlined in [this](https://github.com/ministryofjustice/github-collaborators) repository.

**Comment by mitchdawson1982** [comment]
No value in completing this ticket until we have some external collaborators (Other than Emile).

**Comment by jennycasanova** [comment]
Discussed at backlog refinement 10.11.22 agreed to close ticket as not required at this point as no new joiners.
