### ISSUE TITLE
Improve Folder Structure

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops-monitor#4]
Dashboards should be split into folders based on function or product.  Currently everything resides in the "Provisioned" folder.

**Comment by ASTRobinson** [comment]
some progress made but working through some errors found in the logs and missing Kubernetes default dashboards ![image.png](https://images.zenhubusercontent.com/622a0d0186e6697a53098149/338f28cb-b19d-40ec-b902-d09fec55e747)

WIP branch: https://github.com/ministryofjustice/nvvs-devops-monitor/tree/grafana-folders
