### ISSUE TITLE
🧓 `set-output` deprecated 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops-monitor#46]
The below message appears in current deployments, this should be rectified.

"The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"

**Comment by mitchdawson1982** [comment]
Updated both the aws-credentials and kube-tools packages that are part of the github action deplotment.

**Comment by ASTRobinson** [comment]
Dependabot updates have now been completed and also tested out 'node16' version of 'configure-aws-credentials' to remediate node12 warnings. - all tested and working successfully.
