### ISSUE TITLE
🔢 Map account_ids to environment

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops-monitor#58]
As someone reading the NACS [dashboard](https://monitoring-alerting.staff.service.justice.gov.uk/d/CFhQiFxnk/network-access-control?orgId=1), it is not clear which environment metrics are which, they all have the same title in the legend. 

![image](https://user-images.githubusercontent.com/26419401/200827493-e3c62e8b-b4c1-46cd-a1ef-84e73e820deb.png)

That or they have "Errors from Account 123456789". It would be nice to have 123456789 map to "Production" or whatever the relevant environment is.

**Comment by ASTRobinson** [comment]
[PR86](https://github.com/ministryofjustice/nvvs-devops-monitor/pull/86) has added a dropdown list for each environment and I have renamed any legends where possible but could not find an easy way to replace/rename the account id on the panels. 

![image.png](https://images.zenhubusercontent.com/622a0d0186e6697a53098149/cdb75735-2b5d-4b13-ac91-002f71336857)
