### ISSUE TITLE
NACS PreProduction Dashboards

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops-monitor#6]
There is currently no method of seeing PreProd for NACS.

**Comment by ASTRobinson** [comment]
following the merge of [PR86](https://github.com/ministryofjustice/nvvs-devops-monitor/pull/86) we have now added an environment dropdown to differentiate between the environments (Dev / Pre-Prod / Production). 

![image.png](https://images.zenhubusercontent.com/622a0d0186e6697a53098149/2b23b9b4-a77e-4d62-b3ca-3e0891416f38)
