### ISSUE TITLE
🐛 Monitor Terraform Provider Versions

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops-monitor#64]
Use dependabot to monitor the required version [here](https://github.com/ministryofjustice/nvvs-devops-monitor/blob/main/versions.tf) and create a PR if a new version is created. 

```
terraform {
  required_version = ">= 1.2.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.25.0"
    }
  }
}
```

This is now two minor versions out of date.

**Comment by mitchdawson1982** [comment]
### Current path for terraform monitoring is /terraform

 - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"

### Error unable to locate .tf
Dependabot couldn't find a <anything>.tf
Dependabot couldn't find a .tf.

Dependabot requires a .tf to evaluate your Terraform dependencies. It had expected to find one at the path: /terraform/<anything>.tf.

If this isn't a Terraform project, you may wish to disable updates for it in the .github/dependabot.yml config file in this repo.

### Terraform version file is in the root directory so path needs to be changed in the dependabot block.

**Comment by Gary-H9** [comment]
https://github.com/ministryofjustice/nvvs-devops-monitor/pull/65
